pool_info:
  default_res: Chia reference pool
  name: The Reference Pool
  logo_url: https://www.chia.net/img/chia_logo.svg
  description: (example) The Reference Pool allows you to pool with low fees, paying out daily using Chia.
welcome_message: "Welcome to the reference pool!"
pool_fee: 0.01
pool_url: http://192.168.2.107
min_difficulty: 10
default_difficulty: 10
authentication_token_timeout: 5
default_target_puzzle_hash: txch1h8vdax8vtspx7yt8kz6cwu2awymlgwmdr4qts8v643kusd2lmc5qht7ltq # 396
pool_fee_puzzle_hash: txch1jhydnk47xl40jn3pgwjd708uk2wqzqexagy9xxjcwt2qeaumv3fqcrw6e2 # 226
wallet_fingerprint: 3967641394
wallet_id: 1
partial_time_limit: 25
partial_confirmation_delay: 30
scan_start_height: 1000
collect_pool_rewards_interval: 600
confirmation_security_threshold: 6
payment_interval: 600
max_additions_per_transaction: 400
number_of_partials_target: 30
